sudo: false
dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - valgrind

before_install:
  - pip install --user cpp-coveralls

script:
  - ./scripts/build_release.sh
  - ./scripts/test.sh
  - ./scripts/clean.sh
  - ./scripts/build_debug.sh
  - ./scripts/test.sh
  - ./scripts/valgrind_test.sh
  - ./scripts/clean.sh
  - ./scripts/build_coverage.sh
  - ./scripts/test.sh

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*gmock.*" -E ".*CMakeFiles.*" -e "build/test"
